server.port=8086
spring.application.name=notification-service
springdoc.api-docs.path=/v3/api-docs
springdoc.server-url=http://localhost:8090

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/digital_wallet_notification
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka Client
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.type.mapping=com.wallet.admin.dto.KycNotificationEvent:com.wallet.common.dto.KycNotificationEvent,com.wallet.notification.dto.KycNotificationEvent:com.wallet.common.dto.KycNotificationEvent

# Mail Configuration (Example for Gmail/Mailtrap)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khasimbasha5757@gmail.com
spring.mail.password=oxoo doza owtd dwxy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.connectiontimeout=5000
spring.mail.properties.mail.timeout=5000
spring.mail.properties.mail.writetimeout=5000

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=Notification and Messaging Service
info.app.version=1.0.0
management.tracing.enabled=${TRACING_ENABLED:true}
management.tracing.sampling.probability=${TRACING_SAMPLING_PROBABILITY:1.0}
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
spring.jackson.time-zone=Asia/Kolkata
