sonar.projectKey=digital-wallet-system
sonar.projectName=Digital Wallet System
sonar.sourceEncoding=UTF-8
sonar.java.source=17
sonar.exclusions=**/target/**,**/.sonarlint/**,**/.metadata/**,**/tmp_pdf/**
sonar.coverage.exclusions=**/*Application.java,**/config/**,**/dto/**,**/entity/**,**/repository/**,**/filter/**,**/exception/**,**/util/JwtUtil.java,**/controller/Internal*.java,**/common/dto/**
